# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Linear Algebra to iPhone 1
author: Yoav Palti
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: linear_algebra_to_iphone.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/yoav-palti/linear-algebra-to-iphone  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true

#sphinx:
#  config:
#    mathjax3_config :
#      loader:
#        load: ['input/tex', 'output/svg']
